name: Dependency Review

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    uses: eclipse-fennec/.github/.github/workflows/reusable-dependency-review.yml@227b1dfa5f323fdd6d857d0a61fbaaf6e7288716 # v1.0.0
